apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wafflebear.fullname" . }}-redis-sentinel
  labels:
    app.kubernetes.io/name: redis-sentinel
    app.kubernetes.io/part-of: wafflebear
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-sentinel
      app.kubernetes.io/part-of: wafflebear
